### ISSUE TITLE
 Persistent_ptr - no error when using polymorphism indirectly

### ISSUE THREAD

**Issue by mramotowski** [pmem/issues#150]
It is possible to initialize persistent pointer's as in example below:
```
    persistent_ptr<my_union> pp;
    persistent_ptr<p<my_struct>> pp2;
    persistent_ptr<my_second_struct> pp3;
```

but it should not be possible because persistent_ptr.hpp does not support polymorphism.

my_union, my_struct, my_second_struct:

```
struct my_struct
{
    virtual void func(){};
    int value;
};

struct my_second_struct
{
    my_struct obj;
};

union my_union
{
    struct my_st
    {
        virtual void func(){};
        int int_value;
    };

    double double_value;
};
```

**Comment by tomaszkapela** [comment]
Ok, so I'll start with the polymorphic member.

If you declare a member within a persistent_ptr not as a p<T> or persistent_ptr<T> it is treated as a volatile member. That is why you didn't get a compile time warning. AFAIK, there is no way to iterate, in compile time, through all members of a class and to static asserts.

As for the union... The is_polymorphic type trait does not check unions, as they cannot be polymorphic by design. At the same time, we shouldn't forbid users from taking advantage of unions.

This is an issue that I believe is not fixable in code. I will make it clear in the documentation.

**Comment by mramotowski** [comment]
Verified on 1.0+b1-243-ge207f87
