### ISSUE TITLE
Should have an option to disable msync() for tests

### ISSUE THREAD

**Issue by toddlipcon** [pmem/issues#158]
When developing against nvml, it's common to not have actual pmem hardware available, and be using normal local files instead. This makes tests run very slowly, as the library uses msync() instead of pcommit.

It would be useful to have an API or environment variable to stub out msync for the purposes of testing.

**Comment by krzycz** [comment]
There is one:
```shell
export PMEM_IS_PMEM_FORCE=1
```
would force using `pmem_persist()` instead of `msync()`.
This environment variable is described in *libpmem* man page, but it actually works for all the *libpmem**** libraries.

**Comment by pbalcer** [comment]
And just to be clear, you don't need actual NVDIMMs to write software using libpmemobj, you can emulate pmem using regular DRAM - this will provide you with more accurate performance numbers.

There is a [blog post](http://pmem.io/2016/02/22/pm-emulation.html) we recently published that talks about this very topic.

**Comment by toddlipcon** [comment]
Sorry to reopen this, but I think the environment variable isn't quite sufficient. Since NVML is embedded in other applications (eg Kudu), it would be nice to be able to support our own configuration mechanisms rather than the env var. For example, we typically would want to use a gflag for something like this.

Any chance of exposing this same functionality as a parameter when opening a pool? The env var seems to be read very early in initialization, so using setenv() isn't enough to override it.

**Comment by andyrudoff** [comment]
Hi Todd,

Can you explain your use case a little more?  My worry is this: this is a debug feature that is easily misunderstood.  I definitely would not want a command-line option on a program to enable this, and exposing an API to enable it really sends the wrong message that it is generally useful.  By setting this debug feature, you are fooling the library (and the program using it) into thinking that cache flushes are sufficient to make something persistent when they clearly are not (or it would've been returning true already).  Since the invention of the `pmem_is_pmem()` function, we have discovered corner cases where it really isn't safe to skip `msync()` and we're working on tightening up the definition of when exactly it can return true.

So I think it should be very obvious and in-your-face when you're forcing this for a test.  Can you tell us why something like the following is not viable?

```
$ PMEM_IS_PMEM_FORCE=1 ./run_my_test
```

Thanks.

**Comment by toddlipcon** [comment]
The particular use case I'm hitting is that it's very common for developers to run tests directly from the binary. For example in Kudu, a developer is likely to run build/latest/bin/cfile-test to test their change while they're developing. This developer might not know that this test happens to be parameterized such that it will run against an NVM cache implementation (the dev is just trying to test some new encoding or non-NVM-related thing, for example).

If they don't know to (or don't remember to) set the env var, then this will slam their hard drive with msyncs and take tens of minutes to run. So, in the context of the test case, at runtime, I'd like to enable PMEM_IS_PMEM_FORCE so that the test always runs reasonably quickly. From the perspective of test coverage, the msyncs don't add anything, since we aren't power-cycling the machine.

Another use case outside testing is that there is actually some value to use our nvm cache implementation against /dev/shm -- it won't persist across a power cycle, but it would persist across a process restart. For example, the user might want to upgrade to a new version of Kudu and keep their cache hot after the restart. I suppose if it's configured against /dev/shm, then the msync() won't cost a ton, but it is an extra syscall which isn't necessary for this use case as far as I can think.

**Comment by andyrudoff** [comment]
Thanks, that helps.  Note that for both cases you mention, calls to `pmem_persist()` and to `msync()` are both unnecessary (but I do grant you that calling `pmem_persist()` when it is unnecessary is not nearly as annoying as calling `msync()` when it is unnecessary).

Since libpmem does not make this decision for you anywhere, there must already be code in Kudu that does:

```
if (saved_value_of_pmem_is_pmem_call) {
     pmem_persist(...);
} else {
    msync(...);
}
```

So what about first factoring all those if statements into one convenient location (perhaps that's already done) and changing it to something like:

```
if (!skip_pmem_flush_flag) {
    ...do the logic to decide what type of flush to use...
}
```

Then you get what you want without me adding what I consider a potentially dangerous API to libpmem.

Note that if you hate this idea, you could still implement it yourself by simply doing this after the call to `pmem_is_pmem()`:

```
if (skip_pmem_flush_flag) {
    saved_value_of_pmem_is_pmem_call = 1;   /* just live with the pmem_persist() overhead */
}
```

What do you think?

Thanks.

**Comment by toddlipcon** [comment]
We're now using libpmemobj - my impression is that the libpmemobj library itself makes a lot of calls to pmem_persist? The branching logic you mentioned is the indirection within pmemobj where it assigns pop->persist_local:

```

        if (pop->is_pmem) {
                pop->persist_local = pmem_persist;
                pop->flush_local = pmem_flush;
                pop->drain_local = pmem_drain;
                pop->memcpy_persist_local = pmem_memcpy_persist;
                pop->memset_persist_local = pmem_memset_persist;
        } else {
                pop->persist_local = (persist_local_fn)pmem_msync;
                pop->flush_local = (flush_local_fn)pmem_msync;
                pop->drain_local = drain_empty;
                pop->memcpy_persist_local = nopmem_memcpy_persist;
                pop->memset_persist_local = nopmem_memset_persist;
        }
```

**Comment by andyrudoff** [comment]
Well damn :-)

I really don't like the idea of an API to set this.  I can see myself writing a very strong description in the man page on how you should never call it.

The other idea we came up with was to postpone checking the PMEM_IS_PMEM_FORCE variable until later, say, until the first call to `pmem_is_pmem()` which in this case would be triggered when Kudu tries to open the libpmemobj pool.  This would allow you to call `setenv()` during your argument processing and have it take effect.

**Comment by toddlipcon** [comment]
I think that would work fine for our purposes

**Comment by andyrudoff** [comment]
@krzycz what do you think?  If we make this change, I suggest documenting the behavior in the libpmem man page where PMEM_IS_PMEM_FORCE is described and writing a tiny unit test for it so @toddlipcon  can depend on it.

**Comment by krzycz** [comment]
Well, this should be quite easy to implement, and if I'm not missing anything, it would not break the existing tests depending on PMEM_IS_PMEM_FORCE flag. So yes, I'm fine with that.
