### ISSUE TITLE
tx_range_cache size calculated to be exactly 8192 bytes?

### ISSUE THREAD

**Issue by huwan** [pmem/issues#159]
libpmemobj/obj.h

```
#define	MAX_CACHED_RANGE_SIZE 32
#define	MAX_CACHED_RANGES 127 /* calculated to be exactly 8192 bytes */

struct tx_range_cache {
        struct { /* compatible with struct tx_range */
                uint64_t offset;
                uint64_t size;
                uint8_t data[MAX_CACHED_RANGE_SIZE];
        } range[MAX_CACHED_RANGES];
};
```
but both `sizeof (struct tx_range_cache)` and `sizeof (struct tx_range_cache) + OBJ_OOB_SIZE` are not 8192 bytes. Am I missing something? 

Related commit: [obj: increase range cache size](https://github.com/pmem/nvml/commit/7b5ed84)

**Comment by pbalcer** [comment]
Yup, I made a mistake when changing that.

The reason I wanted the range cache to be of exactly that value is because it exactly matches class allocation size so that there's no unused wasted memory (due to internal fragmentation).

I'll add a static assert to make sure that the tx_range_cache struct size does indeed match the 8 kilobytes I intended it to be.

Thanks for catching this.
