### ISSUE TITLE
make: failure when installing experimental libraries without preinstalled doxygen

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#205]
```
#make EXPERIMENTAL=y install prefix=/usr -j
(...)
install -d /usr/include
install -p -m 0644 include/libpmem.h include/libvmem.h include/libpmemobj.h include/libpmempool.h include/libpmemblk.h include/libpmemlog.h include/libvmmalloc.h include/librpmem.h /usr/include
install -d /usr/lib64/pkgconfig
install -p -m 0644 libpmem.pc libvmem.pc libvmmalloc.pc libpmemobj.pc libpmemlog.pc libpmemblk.pc libpmempool.pc libpmemobj++.pc librpmem.pc /usr/lib64/pkgconfig
make[1]: Leaving directory `/tmp/nvml/src'
make -C doc install
make[1]: Entering directory `/tmp/nvml/doc'
doxygen cppobj.Doxyfile
make[1]: doxygen: Command not found
make[1]: *** [doxygen_docs] Error 127
make[1]: Leaving directory `/tmp/nvml/doc'
make: *** [install] Error 2
```
Found in 1.1-114-g3aceb31

**Comment by tomaszkapela** [comment]
`make install` by default installs the documentation to the appropriate libraries. Since you provided you would like to install the experimental packages (C++ included), you have to have Doxygen. I'm not sure this is a bug, but I can propose three possible changes:
- Specifying a separate build target that the install target would not depend on. I don't think that would be any better. It would be more confusing if anything else.
- Print a SKIP message and continue. This however would be hard to spot during the build process.
- Print an ERROR message and stop building. I believe this one is the most appropriate.

**Comment by plebioda** [comment]
I think we should mention about dependency on Doxygen in README file and leave it as it is. If you would like to install experimental components (which includes CPP documentation) you need to have doxygen installed and the error message in this case is clear. It works the same way if you are missing other tools required (e.g. autotools).

**Comment by tomaszkapela** [comment]
Dependency mentioned and C++ is no longer experimental so I think we should fail when building the docs with no doxygen.

**Comment by tomaszkapela** [comment]
Does this issue need any work, or can it be closed?

**Comment by plebioda** [comment]
:+1: for closing the issue. Right now if you want to generate documentation you need to run `make doc`  - and it requires doxygen to generate html documentation for C++. @kkajrewicz are you satisfied ?

**Comment by kkajrewicz** [comment]
👍
Verified on 1.1-798-g16ebf59
