### ISSUE TITLE
make: missing dependency(pandoc) is not handled properly while building the library

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#216]
When building the NVML library a md2man.sh script for converting markdown files into groff man pages is executed and that script depends on external tool called pandoc.  The information about required pandoc utility before building the nvml should be placed somewhere + script should not be executed when the pandoc is missing. The following logs from make utility are printed:
```
(...)
../utils/md2man.sh ./libvmmalloc.3.md LICENSE > libvmmalloc.3
../utils/md2man.sh: line 55: pandoc: command not found
../utils/md2man.sh: line 55: pandoc: command not found
../utils/md2man.sh: line 55: pandoc: command not found
../utils/md2man.sh: line 55: pandoc: command not found
../utils/md2man.sh: line 55: pandoc: command not found
../utils/md2man.sh: line 55: pandoc: command not found
man ./pmempool-create.1 > pmempool-create.1.txt
../utils/md2man.sh: line 55: pandoc: command not found
../utils/md2man.sh: line 55: pandoc: command not found
../utils/md2man.sh: line 55: pandoc: command not found
../utils/md2man.sh: line 55: pandoc: command not found
../utils/md2man.sh: line 55: pandoc: command not found
man ./pmempool.1 > pmempool.1.txt
man ./pmempool-info.1 > pmempool-info.1.txt
man ./pmempool-check.1 > pmempool-check.1.txt
man ./pmempool-rm.1 > pmempool-rm.1.txt
../utils/md2man.sh: line 55: pandoc: command not found
man ./pmempool-convert.1 > pmempool-convert.1.txt
../utils/md2man.sh: line 55: pandoc: command not found
../utils/md2man.sh: line 55: pandoc: command not found
man ./libpmem.3 > libpmem.3.txt
(...)
make[1]: Leaving directory `/home/user/Repos/nvml/doc'
(...)
```

Found in 1.1-256-g48ba5f8

**Comment by kkajrewicz** [comment]
Verified on 1.1-460-gf0491bb

**Comment by chuckcranor** [comment]
Before you could do "make install" without "pandoc" and it would install the libs.
Now "make install" entirely fails without "pandoc"  because of the "set -o pipefail"
in utils/md2man.sh.

Can the documentation be optional, or is "pandoc" going to be required for installation?
If it is going to be required, can you add something to README.md about it?

**Comment by krzycz** [comment]
I'm sure *pandoc* is mentioned in README, but I agree that we need to add a compact list of all the packages/tools that are required to build/test/install NVML. Currently, this information is scattered around the README file, so some dependencies may be overlooked.

Shall we allow to do `make install` w/o documentation? Perhaps, we could - either by providing some flag like: `make install MAN=0` / `make install DEVEL=0|1`, or a dedicated target: `make install_bins` / `make install_doc` (or something like that). This would make it easier for users that do not want to install *pandoc* and/or do not care about (groff) man pages (as markdowns or web-based docs are enough for them).
I believe `make install` should do everything (it's used for building the Linux distros' packages), but if you build NVML by yourself, there could be some way to skip man pages.

**Comment by chuckcranor** [comment]
When building nvml, it already handles things that are optional... for example this kind of thing:

NOTE: Skipping rpmemd because libfabric is missing -- see src/tools/rpmemd/README for details.

It seems to me that the same thing should apply to pandoc - if it is missing, then it should just skip that part and continue.   That way it would match what is does elsewhere in the nvml tree.

The confusing thing in the README is that it only mentions "pandoc" in the "make doc" section (which is after "make install").   Normally by the time you get to "make install" everything is already built and "make install" just copies all the prebuilt files to their destinations.
