### ISSUE TITLE
make error: File format not recognized

### ISSUE THREAD

**Issue by jencce** [pmem/issues#217]
make[2]: Entering directory `/root/nvml/src/libvmmalloc'
ar rv ../debug/libvmmalloc/../libvmmalloc.a ../debug/libvmmalloc/libvmmalloc_all.o
ar: ../debug/libvmmalloc/../libvmmalloc.a: File format not recognized
make[2]: *** [../debug/libvmmalloc/../libvmmalloc.a] Error 1
make[2]: Leaving directory `/root/nvml/src/libvmmalloc'
make[1]: *** [libvmmalloc] Error 2
make[1]: Leaving directory `/root/nvml/src'
make: *** [all] Error 2

# git log -1
commit cfddcb2afcb15ec895c048458106f44feec395f8
Merge: 6667884 bb7d0ef
Author: Krzysztof Czurylo <krzysztof.czurylo@intel.com>
Date:   Fri Aug 5 12:56:45 2016 +0200

    Merge pull request #1059 from marcinslusarz/examples-fix-libuv-detection
    
    examples: fix libuv detection

**Comment by krzycz** [comment]
I really doubt the problem is caused by this commit. It rather looks like corrupted file due to canceled build, etc. Try to run `make clobber && make` and see if it helps, or if you can reproduce it after cleaning up the tree.
Also, it might be a good idea to provide some more info about your system, Linux distro, compiler version, etc... and how `make` is invoked.

**Comment by jencce** [comment]
thanks,  make clobber did the job for me..

i tried make clean several times. what's the difference between clobber and clean?

**Comment by krzycz** [comment]
Ha! In our makefiles, "clean" only deletes some intermediate files (like *.o, *.log, etc.), but not the target binaries (executables/libraries). While "clobber" is more like "distclean" in some other projects.
See the main Makefile for more details on all the global targets.
