### ISSUE TITLE
rpmem: failure when calling rpmem_create() with local pool size that matches the size of remote pool

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#231]
Man page for rpmem_create() says:
`The size of the remote pool must be at least pool_size`

When calling rpmem_create() with local _pool_size_ equal to remote pool of the same size specified in pool set file:
Actual result:
- pool is not created on remote node
- NULL value returned
- errno 27 (EFBIG - File too large) is set

Expected result:
- pool is created on remote node
- valid remote pool pointer returned
- errno is not set

Found in 0.1-2720-gf432a72

**Comment by plebioda** [comment]
This is because the remote pool has pool header at the beginning which is 4k. The pool header is not accessible by client. Similar situation would occur if you would create multi-part pool on remote node:
PMEMPOOLSET
32M path1
32M path2

You cannot assume the pool size is 64M because both parts contains 4k pool header at the beginning.

**Comment by kkajrewicz** [comment]
Verified on 1.1-595-gbc05190
