### ISSUE TITLE
pmempool: common.c  Memory Error - Use-after-free

### ISSUE THREAD

**Issue by mramotowski** [pmem/issues#309]
There is a possibility of memory usage in lines 413-418 after it is freed in line 405. Found using clang_static_analyzer.
https://github.com/pmem/nvml/blob/master/src/tools/pmempool/common.c#L413

Found on 1.1-869-g3af8428

**Comment by plebioda** [comment]
This is a false-positive. The clang-analyzer assumes the freed element can be still at a head of the list. But LIST_REMOVE macro sets the lh_first field throught the le_prev pointer.

There is an issue for this on clang:
https://llvm.org/bugs/show_bug.cgi?id=18222

I'll mark this as external bug because I don't think we should workaround this issue.

**Comment by krzycz** [comment]
@mramotowski - please, verify the fix.

**Comment by mramotowski** [comment]
Verified on 86084af5e4d9026e899dbcb6c5f647b43f3aeff8
