### ISSUE TITLE
Error when compiling with clang and g++

### ISSUE THREAD

**Issue by tomaszkapela** [pmem/issues#324]
When compiling libut.a using **clang version 3.8.1-12ubuntu1** and any of the C++ tests using **g++ (Ubuntu 6.2.0-5ubuntu12) 6.2.0 20161005** I get the following error:
```sh
/usr/bin/ld: obj_cpp_cond_var.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../unittest/ut.o: relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../unittest/ut_alloc.o: relocation R_X86_64_32S against symbol `Ut_pagesize' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../unittest/ut_backtrace.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
```
This does not reproduce on any of the following combinations:
- gcc and g++
- clang and clang++
- gcc and clang++

I marked this as an external bug, because this is what it looks like.

Observed on: 1.1-962-gbab6734

**Comment by kilobyte** [comment]
CPP has been reorganized since -- among other changes, it's no longer a part of libpmemobj proper.  It has its own test harness which doesn't link to ut anymore.  It also works fine for libpmemobj builds compiled with a different compiler than CPP (the latter being even a header-only library...).  Thus, this is an ex-problem.
