### ISSUE TITLE
device DAX: cannot create pool on fresh device

### ISSUE THREAD

**Issue by kkajrewicz** [pmem/issues#330]
Consider pool.set:
```
PMEMPOOLSET
AUTO /dev/dax0.0
```
1) create dax device using ndctl: 
`#ndctl create-namespace -e namespace0.0 -f -m dax `
2) create obj pool on dax device:
`#pmempool create obj pool.set`
3) pool creation on fresh dax device fails:
```
<libpmemobj>: <1> [set.c:1435 util_header_create] Non-empty file detected
<libpmemobj>: <2> [set.c:1763 util_replica_create_local] header creation failed - part #0
<libpmemobj>: <4> [set.c:1828 util_replica_create_local] error clean up
<libpmemobj>: <4> [set.c:335 util_unmap_hdr] munmap: addr 0x7f1c90400000 size 2111832064
<libpmemobj>: <3> [set.c:406 util_unmap_part] part 0x907390
<libpmemobj>: <4> [set.c:409 util_unmap_part] munmap: addr 0x7f1d0e400000 size 2111832064
<libpmemobj>: <2> [set.c:2073 util_pool_create_uuids] replica #0 creation failed
<libpmemobj>: <3> [set.c:1939 util_replica_close] set 0x9072e0 repidx 0
<libpmemobj>: <3> [set.c:406 util_unmap_part] part 0x907390
<libpmemobj>: <3> [set.c:490 util_poolset_close] set 0x9072e0 del 1
<libpmemobj>: <3> [set.c:1939 util_replica_close] set 0x9072e0 repidx 0
<libpmemobj>: <3> [set.c:406 util_unmap_part] part 0x907390
<libpmemobj>: <3> [set.c:444 util_poolset_free] set 0x9072e0
<libpmemobj>: <3> [set.c:152 util_remote_unload]
<libpmemobj>: <2> [obj.c:1052 pmemobj_create] cannot create pool or pool set
error: 'pool.set' -- Non-empty file detected
error: creating pool file failed
```

Found on 1.1-1008-gc3885a5

**Comment by pbalcer** [comment]
That's not a bug, the error message is correct. Your provided a non-empty file - it's not guaranteed anywhere that a newly created device dax is zeroed.

**Comment by plebioda** [comment]
I believe this is exactly the same case if you have a regular non-empty file. You need to remove it first in order to create a pool on it. In case of device dax you can't remove the device using `rm` but you can use `pmempool rm` before `pmempool create`.

**Comment by plebioda** [comment]
Can we close this issue as "won't fix" ?

**Comment by krzycz** [comment]
Hmmm, but in case of a new file, it's guaranteed that it's zeroed. You only need to care about creating pmem pools on existing files. In such case you need to either zero out the first 4-8K, or, as you said, remove and recreate the file.
But how can you zero out device dax if "dd" does not work? "pmempool rm" is some sort of workaround here, but not very convenient. Perhaps we should change the behavior of pmemobj_create() for device dax?
At least, "pmempool create" could have an option for that.

BTW, the error message in the log is quite misleading. It's not the problem with 'pool.set' file that is not empty, but with '/dev/dax0.0', I believe. (Or maybe it really fails because of 'pool.set' file? - then, it's a bug.)

**Comment by plebioda** [comment]
I think `pmempool rm` on device dax is not a workaround but it is the solution for "removing" pool from device dax. Frankly, I would rather see an option to `ndctl create-namespace` which would zero the entire device. Or 

In my opinion we should not change the behavior of `pmemxxx_create()` because it should behave the same way as with regular file - for existing non-zeroed files it simply fails to create a pool.

I think we could add `-f, --force` flag for `pmempool create` which would remove the pool first. How about that ?

I agree the error message could be better but it says that "non empty file detected" in the specified pool.set.

**Comment by krzycz** [comment]
Totally agree with an option for "ndctl create-namespace" or some other command for scrubbing/zeroing memory. (Possibly it could use some dedicated HW command for optimized zeroing (if available), rather than memset()).

As for "pmemxxx_create()" - I'm not going to modify it - just thinking out loud.
Some time ago, we decided that to protect users from accidental overwriting an existing pool and/or other data file, pmemxxx_create() would fail if the file is not empty (in practice, the first 4K must be zeroed). However, we may relax this requirement and fail only, if the first 4K contains a valid pool header. If there is some garbage / other data there - we could continue with new pool creation.
But I'm not sure if this would help in this case - probably not.
Another option could be to remove this condition completely (also for regular files).

:+1: for "-f" option for "pmempool create".

**Comment by kkajrewicz** [comment]
Short option does not work:
```
# pmempool create obj /dev/dax0.0
error: '/dev/dax0.0' -- Non-empty file detected
error: creating pool file failed

# pmempool create -f obj /dev/dax0.0
create: invalid option -- 'f'
Usage: pmempool create [<args>] <blk|log|obj> [<bsize>] <file>

# pmempool create --force obj /dev/dax0.0 
```
Last command succeeded.

Verified on 1.2+b1-351-g822afa5

**Comment by kkajrewicz** [comment]
Verified on 1.2+b2-24-g53d2859
