### ISSUE TITLE
pmempool transform: difference exit code in unsuccessful operations 

### ISSUE THREAD

**Issue by kamdiedrich** [pmem/issues#366]
Consider below pool set file:
```
PMEMPOOLSET
20M /mnt/psmem_0/part.1
20M /mnt/psmem_0/part.2
```
And following target file:
```
PMEMPOOLSET
20M /mnt/psmem_0/part.1
20M /mnt/psmem_0/part.2
REPLICA
10M /mnt/psmem_0/replicaPart.1
15M /mnt/psmem_0/replicaPart.2
```

after calling pmempool transform function will return -1 but on Linux from the same example we got 255. We should unify return codes on both OS-es.

Found on: 1.2-rc3

**Comment by plebioda** [comment]
What do you mean `pmempool_transform` or `pmempool transform` ? If the latter then on Linux the value returned from an application is converted to unsigned 8bit value that is why you get 255 instead of -1.

However I think the returned value from pmempool should not be negative and < 128, the general error should return 1:
See: http://www.tldp.org/LDP/abs/html/exitcodes.html

@wojtuss Could you please take a look at exit codes returned by all `pmempool` commands ?

**Comment by wojtuss** [comment]
@kamdiedrich , please verify the issue

**Comment by kamdiedrich** [comment]
Verified on: 1.2+wtp1-48-g22c923a
