### ISSUE TITLE
libpmemobj atomic allocator regression (deadlock)

### ISSUE THREAD

**Issue by simondsmart** [pmem/issues#433]
Having pulled the latest nvml code, I have uncovered a regression in the atomic allocation functionality.

If an atomic persistent allocation is performed from inside the construction function of another atomic persistent allocation, this now deadlocks. Previously the allocations proceeded normally (and as far as I can tell) the error handling and exceptional conditions were handled correctly.

The relevant (sequential) git commits are:

58e010c667fe65a593b308cc4b4730dbc479dd9a   // Fails (deadlock)
2d4c1f93ffe9b4bb6484e1cab45b044a546f59ef   // Doesn't compile (likely culprit) [ @pbalcer ]
ae561e88e846587002c4047868956b0538cd14fe   // Works correctly

Please see attached a (strongly) reduced test case demonstrating the issue: [pmem_recursive_testcase](https://gist.github.com/simondsmart/5052e650c3e2ff0a670936c60ae897a7)

I appreciate that it is possible that this functionality has been de-supported to simplify the allocation pathway, and this can be worked around by inverting the flow control around construction of more interesting objects. But it would be great if it could be retained, if only for elegance sake.

In particular, this behaviour is really useful for constructing objects with variable sized components (such as string-based tags, or similar), where semantically that construction behaviour really belongs in the constructor of the outer object.

Many thanks for the great work!

**Comment by pbalcer** [comment]
The new behavior is actually better. Allocation from within a constructor was never safe and could led to persistent memory leaks. Consider a situation in which the inner allocation succeeded, but the outer one was interrupted by a power failure. Because both of those allocations were atomic only in their own scope, the first one has been correctly allocated, and the memory it occupies is marked as "used", the second one is gone. This leads to a situation in which there's no reference to the first object and you would have to write custom recovery mechanism that uses internal collections to find that missing object.

For situations like this one, I recommend using transactions. We've had similar dilemmas with our C++ bindings and constructors of atomically allocated classes, but there's simply no way around the issue I've described above.

You might also be interested in the #pmem/issues/415 (more info in the recent blog post) feature that will allow you to **safely** reserve multiple objects, modify them in arbitrary ways, and publish them in a single atomic call:

``
struct pmemobj_memops m;

TOID(OuterType) outer =  POBJ_RESERVE(pop, OuterType, &m);
D_RW(outer)->innter =  POBJ_RESERVE(pop, InnerType, &m);

POBJ_PUBLISH(pop, &m);
``

Glad you like our library :)

**Comment by pbalcer** [comment]
@simondsmart Is it OK for me to close this issue or do you have any suggestions how we might make this work-flow correct and usable?

**Comment by simondsmart** [comment]
@pbalcer Sorry for the slow response, we were ate a project meeting in Brussels.

We have chosen to not make use of the transactions API for a number of reasons. I note that we have potentially subtly different goals. I am anticipating that the failure you described would be a rare one, and ultimately our concern is avoiding corruption of the memory structures. We care that from the perspective of another reading or writing process that opens the pool after failure, the data accessible by our data structures in persistent memory is consistent and that changes to this data structure are logically atomic.

We don't actually care all that much if we create (very occasional) orphaned objects. Apart from the relatively small amount of memory used, that is indistinguishable from the entire operation failing atomically.

Indeed, we are actually writing (and persisting) data blobs into one pool, and then later inserting them into an indexing structure in a different pool (this is to match the structure of the backend of another piece of software), so there is a much larger window for potentially orphaning much larger blobs of data in that context. This is why potentially inverting the control flow doesn't concern me too much here.

That said, your reserve/publish API sounds more interesting. Am I correct in understanding that a pair of pmemobj_reserve/pmemobj_publish (with the appropriate constructor functions called in the middle) is equivalent to using pmemobj_alloc? Which blog post were you referring to? There does not seem to be any mention of these functions in the published man page.

One question, if the two different reserved regions attached to a pmemobj_memops are in different pools will this still succeed in an atomic fashion? I presume not?

**Comment by pbalcer** [comment]
I would be very reluctant to making the change that would restore this functionality, even though you could reasonably implement an application that works around the problem I've described, there's very little performance penalty for using the API as intended. I'd suggest measuring the performance difference between using transactions vs atomic allocations, you might find out that it's not that big. And given a very long running system, you will eventually run out of memory due to that tiny leak.

A pair of `pmemobj_reserve` and `pmemobj_publish` is indeed equivalent to a single atomic allocation. If you go to the `palloc_operation` function in palloc.c as is currently on master, you will notice that it is implemented with the notion of reserve/publish anyway, it's just not exported as public API.

I'm referring to this [post](http://pmem.io/2017/01/25/libpmemobj-jan-plans.html). This is still very much a work in progress, so there's no mention in the manpages. I'm planning on finishing the work somewhere in next month.

The internals of our library were not designed to support operations between two pools as that would create an ordering issue in regards to opening the pools. Imagine a situation when the two pools have a cross reference in the recovery segment, so that the first pool requires the second pool to be opened in order to perform recovery, but the second pool has the same requirement for the first pool. And that's just one problem this notion creates. I'm afraid you are not your own on this one.

**Comment by simondsmart** [comment]
Understood. I will have a look at the extent to which we can use `pmemob_reserve` and `pmemobj_publish`.

RE long term memory leaks; one of the constraints we operate under is that we have to have really straightforward and bulletproof processes for the operators (noone wants to be called at 4am because things aren't working).

As such, our design uses completely separate data pools for storing the data associated with each 12 hour operational period. This means that (a) if there are significant failures, the recent data can just be wiped and the entire process rerun, and (b) old data can be easily and very safely removed in bulk once it expires, both by just removing the pools (or recycling them). This also has the nice side effect of minimising the risks associated with that small data leak.

That said, I completely understand trying to close that leak in the library. Could I suggest that it would be nice to have the allocation fail (NULL return with an error) when allocations are nested rather than deadlock.

The inter-pool relationship doesn't surprise me - but is easily worked around (we already assumed there was no reasonable atomic behaviour across pools).

**Comment by pbalcer** [comment]
Let me know if you figure something out that works. If there's no other alternative, I can, at the cost of an additional pair of `pthread_mutex_unlock` and `pthread_mutex_lock`, make an opt-in that enables the old behavior (but I'd really rather not :))

As for failing instead of deadlocking: there's a cost associated with every check we do :) In this case, it would be an additional TLS variable that indicates whether an allocation is in progress. I'll think about this one, but we will have to probably settle for a mention in the man page and an assert in debug version of the library.

**Comment by simondsmart** [comment]
I have added some factory functionality to our code to build requisite objects piecewise (with appropriate error reporting on failure). And the worst available failure mode is the same as it was before (with potentially lost blocks), but somewhat more explicit that this could happen.

Thanks for your help.
