### ISSUE TITLE
Emulate Persistent Memory

### ISSUE THREAD

**Issue by Legend147** [pmem/issues#487]
Some Non Volatile Memory (e.g. Phase Change Memory) has high write latency and low write Bandwidth. So how to emulate the Persistent Memory Latency and Persistent Memory Bandwidth ?
Otherwise,  the article “System Software for Persistent Memory” proposed PM Emulation Platform( PMEP），it partitions the available DRAM memory into emulated PM and regular volatile memory, just like memmap ?

**Comment by andyrudoff** [comment]
Since the point of Persistent Memory is to allow applications direct load/store access, there isn't a software interception point for stores.  So I know of no way to emulate the performance of a specific memory technology using software.  Hardware emulation seems possible, in the form of a specially-made DIMM or perhaps a special platform that changes the performance of certain memory ranges.  Even so, I don't know of any good performance emulators.

Closing this issue since it is not an issue with the library.  Please feel free to continue the discussion on the "pmem" google group.
