### ISSUE TITLE
Windows/Linux different errno depending on OS

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#507]
Several functions return different errno:
pmemblk_check(nullptr), pmemlog_check(nullptr) and pmemobj_check(nullptr):
Windows errno  22; Linux errno  14;

pmemlog_open(nullptr):
Windows errno  22; Linux errno  14;

pmemlog_create(non_existent_dir, 2 * PMEMLOG_MIN_POOL, S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP | S_IROTH | S_IWOTH):
Windows errno  22; Linux errno  21;

pmemlog_create(nullptr, 0, S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP | S_IROTH | S_IWOTH):
Windows errno  22; Linux errno  14;

Behaviour of above functions is the same on both oses.
Found on: 1.2+b1-40-g4d9aa1b

**Comment by krzycz** [comment]
**1) *pathname* is NULL/nullptr**
**Linux:** open() sets errno to EFAULT (14) - *pathname* points outside your accessible address space.
**Windows:** Because of how Unicode support is implemented, each *pathname* (UTF8-encoded) is first converted to UTF16. In case of nullptr, the conversion function fails and it sets errno to EINVAL (22).
We could set it to EFAULT, but there could be some side effects, as the conversion routine may be used for other purposes as well.
Moreover, if you pass an invalid pointer (not NULL, but 0xFEEDBEEF or something like that) to pmemxxx_open() as a *path*, then the behavior on Linux could be the same as for NULL, while on Windows it may result in program crash.

**2) *pathname* pointing to the non existent directory (not a file)**
**Linux:** open() sets errno to EISDIR (21) - *pathname* refers to a directory and the access requested involved writing (that is, O_WRONLY or O_RDWR is set).
**Windows:** _wopen() sets errno to EINVAL (22).

My recommendation is to adopt the program/test to not depend on the actual errno value. I'd only check if it's non-zero (if you expect there should be some error code set). Definitely, we're not going to change/override the errno values that are set by system functions just to make them identical on both OS-es.
