### ISSUE TITLE
obj:some questions about "POBJ_FLAG_NO_FLUSH"

### ISSUE THREAD

**Issue by xuezheng-zhuzibaijia** [pmem/issues#528]
There is something really troubling me when I try to use transaction in multi-thread way(I had to).So I write a basic program to test.In order to improve the performance,I use 'pmemobj_tx_xadd_range' and 'POBJ_FLAG_NO_FLUSH' instead of 'pmemobj_tx_add_range',besides,I assume the whole change in the memory would be flush to file when 'COMMIT'.The sub-function each thread would execute is like following:
`void mins_a(void* arg)
{PMEMobjpool * pop = (PMEMobjpool *)arg;
    TOID(struct root) myroot = POBJ_ROOT(pop,struct root);
    int b;
    TX_BEGIN(pop)
    {
        do
        {
            b = D_RO(myroot)->a;
            pmemobj_tx_xadd_range(myroot.oid,TOID_OFFSETOF(myroot,a),POBJ_FLAG_NO_FLUSH,sizeof(int));
        }
        while(!__sync_bool_compare_and_swap (&(D_RW(myroot)->a),b,b-1));
    }
    TX_END
}`
But this didn't work,turns not change at all.So I reference the "../libpmemobj/tx.c".In the function 'tx_pre_commit' ,it called 'tx_flush_range' which should flush the change to the file.but actually didn't.
 I am willing to receive your brilliant idea.

**Comment by krzycz** [comment]
There is a number of issues with your example.

First, the memory modified within a TX (regions added to undo log using `TX_ADD`, `pmemobj_tx_add_range`, `pmemobj_tx_xadd_range`, ...) is normally flushed at TX COMMIT and you don't need to set any flag for it. The `POBJ_FLAG_NO_FLUSH` flag meaning is not what you said. It completely disables flushing the object's data to persistence and should be used only if the program takes the full responsibility for that (which is not the case, I guess). If this flag is set, libpmemobj would only care about flushing its metadata (i.e. the allocator metadata, undo logs, etc.), but not about the user data.
This flag was introduced to avoid double flushing the data, like in the example below:
```c
void obj_init(struct my_obj *obj)
{
    memset(ptr, 0, sizeof(*obj));
    obj->type = UNKNOWN_TYPE;
    pmem_persist(ptr, sizeof(*obj)); /* !!! */
}

TX_BEGIN(pop) {
    /* typical case - the library is responsible for flushing the data */
    pmemobj_tx_add_range(oid1, 0, sizeof(struct my_obj));
    struct my_obj *o = pmemobj_direct(oid1);
    o->type = TYPE1;
    o->value = 5;

    /* special case */
    pmemobj_tx_xadd_range(oid2, 0, sizeof(struct my_obj), POBJ_FLAG_NO_FLUSH);
    /*
     * This function initializes the object and flushes its data.
     * No need to do it again at TX_COMMIT.
     */
    obj_init(pmemobj_direct(oid2));
    /* ... */
 } TX_END
```
So, I'd rather discourage you from using this flag unless you really know the flushing is done elsewhere.

The other issue I noticed in your code is the wrong order of the arguments to `pmemobj_tx_xadd_range` - flags should be the last argument. Perhaps you made a mistake only in this example, but please double check your code.

Another problem is the do/while loop inside TX, with a call to `pmemobj_tx_xadd_range`. If CAS fails, you'd call `pmemobj_tx_xadd_range` multiple times for the same region. It's not a critical issue, but a huge performance penalty. The libpmemobj checks if given region is already in undo log, and would not add it again. Otherwise it could result in a rapid growth of the undo log and likely end up with OOM.
Also, if you think `pmemobj_tx_xadd_range` would snapshot the latest value of `D_RO(myroot)->a` (if it was modified by another thread), you're wrong. As I said, only the first call to `pmemobj_tx_xadd_range` have any effect, so it could be moved outside the loop.

And last but not least - all the NVML libraries are designed to be thread-safe, so there's nothing wrong in using them in a multi-threaded programs. The libpmemobj library provides convenient mechanisms to provide thread synchronization, so if you need to access the same object from multiple threads, you can embed PMEM locks in your objects and use TX_BEGIN_LOCK to make sure only one thread at the time is accessing given object/memory region. I'm not sure why you're not doing it that way, but maybe your example is to simple to help me understand the whole idea and give you some better guidance. 

Just in case - if you didn't see it yet, here is a link to the libpmemobj man page:
http://pmem.io/nvml/libpmemobj/, on which you can find the links to a few articles on our blog - a mini-tutorial on pmemobj API, transactions, threading, etc.

Hope this helps.

**Comment by xuezheng-zhuzibaijia** [comment]
Many thanks for your help and I am really sorry for carelessness of my code. Your advice really help to find a new way to achieve my project.Your help was greatly appreciated.
