### ISSUE TITLE
libpmemobj:How can I use "pmemobj_tx_alloc" in seperate threads?

### ISSUE THREAD

**Issue by xuezheng-zhuzibaijia** [pmem/issues#576]
```
#include <stdio.h>
#include <stdlib.h>
#include <libpmemobj.h>
#include <pthread.h>
POBJ_LAYOUT_BEGIN(test);
POBJ_LAYOUT_ROOT(test,struct root);
POBJ_LAYOUT_TOID(test,int);
POBJ_LAYOUT_END(test);
PMEMobjpool * get_pool(){
    PMEMobjpool * pop = pmemobj_open("testfile",POBJ_LAYOUT_NAME(test));
    if(pop==NULL){
        pop = pmemobj_create("testfile",POBJ_LAYOUT_NAME(test),PMEMOBJ_MIN_POOL,0666);
        if(pop==NULL){
            perror("pop create failed");
            exit(-1);
        }
    }return pop;
}struct root{
    TOID(int) a;
};
void * malloc_int(void*arg){
    PMEMoid t = pmemobj_tx_alloc(sizeof(int),TOID_TYPE_NUM(int));
    int * tmp = (int *)pmemobj_direct(t);
    *tmp = 10;
    return tmp;
}
int main()
{
    PMEMobjpool * pop = get_pool();
    TOID(struct root) root = POBJ_ROOT(pop,struct root);
    TX_BEGIN(pop){
        pthread_t temp;
        pthread_create(&temp,NULL,malloc_int,NULL);
        int * t;
        pthread_join(temp,(void **)&t);
        TX_ADD_FIELD(root,a);
        TOID_ASSIGN(D_RW(root)->a,pmemobj_oid(t));
    }TX_END
    printf("%d",*((int *)(D_RW(D_RW(root)->a))));
    pmemobj_close(pop);
    return 0;
}

```
Here is the codes,which is just a example.In my application,I do need to allocate dynamic memory in threads which all are included in one transaction.But as above,when the program executed in "pmemobj_tx_alloc",the transaction  would abort.I do have read the the blog "Challenges with multi-threads",but unavoidably,I do need multi-threads (which include writes and free operations) in one transaction,which would keep atomicity of  whole database .So please tell me there is another way to use transaction in multi-threads way.and yes the Pi example does no help.

**Comment by krzycz** [comment]
Sorry, the short answer is no - this is not supported.
In current version of *libpmemobj* there can be only one open transaction per thread and only one thread per transaction. This is because the internal data structures that holds the TX state is placed in thread local storage. Thus, it cannot be shared by multiple threads.
From the *libpmemobj* point of view, spawning new thread(s) inside a transaction is simply incorrect and would likely lead to undefined behavior - hang, crash or data corruption.

**Comment by xuezheng-zhuzibaijia** [comment]
Thanks for your advice!After rethinking it,I find another way to achieve the multi-thread allocate/free operation.Before multi-threads,I allocate memory in advance,then in multi-threads,I just allocate from that,so there would be no really allocation in thread,and I record the 'oid' which is going to be free.After multi-threads operations,I free them together.
A little advice,have you guy ever consider to build something like memory pool,which would provide multi-thread way allocate/free operation?

**Comment by pbalcer** [comment]
`pmemobj_tx_alloc()` is MT safe and scalable. The problem here is that transactions have implicit thread scope, which means that you cannot have multiple threads contributing to the same transaction, in other words, you cannot call pmemobj_tx_alloc() from multiple threads and COMMIT the resulting objects in a single transaction. 

A feature which would allow you to do so is currently under review (#415).
