### ISSUE TITLE
rpms: nvml-debuginfo does not building on SLES

### ISSUE THREAD

**Issue by PatrykMatyjasek** [pmem/issues#64]
Packege nvml-debuginfo is not created when rpms are built on SLES.

rpmbuild version:
RPM version 4.4.2.3, and RPM version 4.11.2

**Comment by plebioda** [comment]
We do not set building debuginfo package explicitly in our spec file. This is done automatically on some distros but it is not in other distros. One solution is to use %debug_package macro in spec file but it turns out that this macro produces different results on different distros. On SLES it creates a separate package with debug info for all packages included in spec file, but on Fedora 22 it creates a single nvml-debuginfo package. Thus I think we have 4 options to solve this issue:

1. Leave the decision about building *-debuginfo package(s) to distro's environment settings
2. Use the %debugpackage macro to force building *-debuginfo packages (but the resulting number of packages depends on environment settings).
3. Add explicit rule for building nvml-debuginfo package.
4. Add explicit rules for building *-debuginfo packages - separate for each package.

Any opinions ?

**Comment by krzycz** [comment]
:+1: for :two:

**Comment by kkajrewicz** [comment]
Verified on 0.3+b3-142-g6088956
