### ISSUE TITLE
pmempool rm: order of arguments affects the result

### ISSUE THREAD

**Issue by kamdiedrich** [pmem/issues#650]
Consider following pool set file:
```
PMEMPOOLSET
20M /user/part1
20M /user/part2
```
after call `pmempool rm -s -l ` pool files and pool set file will be removed, but when we call `pmempool rm -l -s ` pool files will be removed and pool set file will stay. 
The order of arguments should not matter. It should be consistent. I think that in this situation pool set file should stay - always when we use -s option.

Found on: 1.3+b1-108-g3451dfd31

**Comment by krzycz** [comment]
First, this is how other tools work - if there are two flags with opposite meaning, the order matters (the last flag overrides previous ones). I.e. try `rm -i -f ./dummy` and `rm -f -i ./dummy`
So, it's not a bug, but the expected behavior.

OTH, perhaps we should obsolete `-s` flag, as this flag alone does not change anything (by default, only pool files/parts are deleted).

@plebioda, is this flag left for backward compatibility?

**Comment by krzycz** [comment]
Feature as designed.
