### ISSUE TITLE
common: set_funcs() - overridden functions are not called

### ISSUE THREAD

**Issue by mglaner** [pmem/issues#727]
**libvmem:**
vmem_realloc() does not call realloc()
vmem_free() does not call free()
vmem_strdup() does not call strdup()

**libpmemobj:**
pmemobj_realloc() does not call realloc()

**libpmemblk, libpmemlog:**
no API function calls realloc() internally

Neither documentation nor pmdk API functions names are clear about which respective function overridden by set_funcs() is effectively called internally.

Found on 1.3+b2-435-gb044451

**Comment by krzycz** [comment]
Each PMDK library needs to allocate some **system** memory (RAM) for its internal purposes (i.e. to manage run-time state, TLS, last error message buffer, etc.). By default, they call standard malloc/realloc/strdup/free in that case. However, some users may prefer to provide their own memory allocator because they do not want or cannot use libc for that. *set_funcs()* allows to specify an alternate set of malloc-like functions that will be used **internally** by PMDK libraries instead of libc interfaces.
It does not affect the behavior/result of the PMDK APIs (i.e. the functions listed above) and what they return. E.g. pmemobj_realloc() always allocates from PMEM, and would never return memory allocated by one of the functions passed to set_func().

**Comment by mglaner** [comment]
Thank you for the answer. It is much more clear now how it works.
