### ISSUE TITLE
tests: wrong skip message

### ISSUE THREAD

**Issue by mramotowski** [pmem/issues#732]
Skip message for some tests provide wrong information about what is needed to run them. This message should give proper information about what is really needed (number of dax devices and their alignments).

pmempool_sync/TEST13, 14, 15, 18, 19, 20, 21
pmempool_transform/TEST22
pmempool_sync_remote/TEST10, 11, 12, 13, 14, 15, 16, 17, 18, 19
pmempool_transform_remote/TEST6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19

**Comment by plebioda** [comment]
@mramotowski could you specify exactly what do you mean? What is current message and what would you expect ?

**Comment by krzycz** [comment]
I guess the problem is that test is first skipped because the number of DAX devices is not enough. And when this is fixed, it skips because the internal alignment of those devices is not as required.
It would be nice to provide all the requirements in the skip message, to the user can configure DAX devices properly.
I have a prototype fix ready, but it requires to modify a lot of TEST* scripts, so it'll take some time.

**Comment by mramotowski** [comment]
What @krzycz wrote, is exactly what I meant.

**Comment by mramotowski** [comment]
Verified on a16db9ef913a45aeaabc2dc3ac76ffda2f59954d
