### ISSUE TITLE
manpage: wrong minimum number of block info in libpmemblk

### ISSUE THREAD

**Issue by PatrykMatyjasek** [pmem/issues#75]
Manpage describe that minimum number of blocks in blk pool is 256.
But real minimum number of block is 512:
```
<libpmemblk>: <3> [blk.c:495 pmemblk_create] path /mnt/psmem_0/myfile bsize 104857 poolsize 33570816 mode 438
(…)
<libpmemblk>: <1> [btt.c:950 write_layout] number of internal blocks: 319 expected at least 512: Invalid argument
```

git describe: 0.1+b16-208-g12c51c1

**Comment by krzycz** [comment]
The information in man page is correct. *(...) the number of __available blocks for the user__ cannot be less than 256.* However, since internally we always have a pool of 256 free blocks, so the __total__ number of blocks must be not less than 512.
Anyway, we need to clarify that in the spec, or change the error message to something less confusing. Or both...

**Comment by PatrykMatyjasek** [comment]
Verified on 0.2-rc1-4-gcdb54dc
