### ISSUE TITLE
tests: test directory on Windows is not created automatically

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/issues#751]
Unlike on Linux, there is no automatic creation of test directory on Windows.

Found on: 1.3+b2-608-g1a8b9ce81

**Comment by krzycz** [comment]
@kasiawasiuta Could you elaborate on what is the problem? Any logs?

**Comment by kasiawasiuta** [comment]
It is regarding $Env:PMEM_FS_DIR and $Env:NON_PMEM_FS_DIR paths defined in testconfig. When either of this paths are nonexistent on Linux, they are automatically created before the rest starts. Imho the same behavior should be implemented on Windows.

**Comment by krzycz** [comment]
Actually, those directories **would be** created if they do not exist. The problem is that before they got created, we do the check if PMEM_FS_DIR really points to pmem device and the test fails on this check.
And this is exactly the same behavior as on Linux.

Ergo, there is no bug - it works the same on Linux and Windows.
I suggest to close this issue and the corresponding PR.

**Comment by krzycz** [comment]
**Update**: Seems like the behavior is different for PMEM_FS_DIR (fail if not exists) and NON_PMEM_FS_DIR (crated if not exists). We need to unify that.

**Comment by kasiawasiuta** [comment]
verified on 1.3+b2-900-g7339f2f9b
