### ISSUE TITLE
rpmem not robust when illegal parameter for target is provided

### ISSUE THREAD

**Issue by RHeideX** [pmem/issues#854]
Pool set on remote node:
> PMEMPOOLSET
> 20M /dev/shm/pool.part0
> 8M /dev/shm/pool.part1
> OPTION NOHDRS

App:
> (...)
> size_t pool_size = 20*1048576;
> void *pool = aligned_alloc(sysconf(_SC_PAGESIZE), pool_size);
> unsigned lanes = 1024;
> target = “root@192.168.0.231@22”;
> RPMEMpool *rpp = rpmem_create(target.c_str(), pool_set_name.c_str(), pool, pool_size, &lanes, nullptr);
> (...)

**Expected:**
rpp = nullptr
**Actual:**
Depending on the system:
- RHEL (Chelsio): function call to rpmem does not return (within reasonable time; takes more than 15 minutes)
- SLES (Chelsio): Segmentation fault

**Note**: Other tested values for target with the same results are for instance: “root:192.168.0.231:22” and “root@.192.168.0.231:22”

Found on: 1.4.2

**Comment by janekmi** [comment]
Which libfabric version do you use?

**Comment by janekmi** [comment]
This issue is covered by [src/rpmem_addr_ext/TEST0](https://github.com/pmem/pmdk/blob/master/src/test/rpmem_addr_ext/TEST0).

libfabric 1.4.2 has a known issue with this kind of strange addresses. libfabric 1.4.3 has fixed this but some later releases also have this problem because of it we have even disabled this test for a some time: pmem/pmdk#2696. Now we are trying to reenable it with pmem/pmdk#2877.

So I recommend to try libfabric 1.6.0.

**Comment by RHeideX** [comment]
Retested with libfabric 1.6.0 with CHelsio on both RHEL and SLES. Neither one of the above mentioned problems occurred.
