### ISSUE TITLE
pmemobj: it is possible to allocate object with size near to range of size_t

### ISSUE THREAD

**Issue by PatrykMatyjasek** [pmem/issues#86]
Steps to reproduce:
1. Create pool with MIN_POOL_SIZE
2. Allocate object with size in range <2^64 - 67, 2^64 - 1>

Expected result
allocation should not be succeded, returned value equal to -1, errno = 12(ENOMEM)

Current result:
Successful allocation, returned value equal to 0, errno = 0

Git describe: 0.2-27-g42ab7e5

**Comment by pbalcer** [comment]
Test overflow bugs are not library bugs. GNU C defines size_t as unsigned integer, so you are effectively allocating between 1 to 63 bytes. This also applies to #85

**Comment by krzycz** [comment]
There is no overflow here (I mean, not in the user code).  The user specifies an allocation size which is close to the limit of size_t, and obviously this is more than they can get.  If the library increases the size to make a space for allocation metadata (allocation header + OOB header) and it results in overflow, then this is a bug in the library.  The user doesn't need to know about the library internals.
`malloc(SIZE_MAX)` returns NULL and sets *ENOMEM*.

Moreover, if you try to make allocation of size `SIZE_MAX - 2 * 64` or even `SIZE_MAX - 1024` (to make sure there is no overflow after adding metadata size), *pmemobj_alloc* will not fail. There will be a small object allocated, but *pmemobj_alloc_usable_size* would return the original (huge) size.
One of the reasons is that internally allocator calculates the number of units (chunks) for given allocation, and such number (aka *size index*) is 32-bit integer. Since the hardcoded chunk size is 256KB, than any allocation size greater than 2^50 results in overflow (size_index > UINT32_MAX) and size_index == 0.

This should be fixed. Also, there must be an information added in the man page about the maximum allocation size (which is limited by some allocator internals), and the proper macro should be defined in *libpmemobj.h*.

**Comment by PatrykMatyjasek** [comment]
Verified on 0.2+b4
