### ISSUE TITLE
How to enable to build daxio on pmdk 1.4

### ISSUE THREAD

**Issue by chunglam1999** [pmem/issues#892]
Please let me know how to enable to build the daxio on pmdk 1.4

**Comment by chunglam1999** [comment]
i have installed ndctl 60.1 but daxio still not being built

**Comment by marcinslusarz** [comment]
In 1.4 we made a mistake of using one flag for 2 features.
The flag is "NDCTL_ENABLE" and the 2 features are daxio and RAS enablement. Shortly before 1.4 release we decided that RAS enablement is not ready, so we disabled it, but didn't realize it was also disabling daxio.

For 1.5 ndctl is planned to be mandatory, so the problem of daxio will also be solved.
However we should probably fix it for the next stable release.
In the mean time you can build daxio by going into src/tools/daxio directory and calling
```make install NDCTL_ENABLE=y```
Don't do it in the top level directory, because it will enable RAS (which is incomplete and not backward compatible).

**Comment by chunglam1999** [comment]
Thanks for help.
